package com.example.mvvmrunningapp.other

object Constants {

    /** DB */
    const val RUNNING_DATABASE_NAME = "running_db"

    /** PERMISSION */
    const val REQUEST_CODE_LOCATION_PERMISSION = 0

    /** SERVICE */
    const val ACTION_START_OR_RESUME_SERVICE = "ACTION_START_OR_RESUME_SERVICE"
    const val ACTION_PAUSE_SERVICE = "ACTION_PAUSE_SERVICE"
    const val ACTION_STOP_SERVICE = "ACTION_STOP_SERVICE"
    const val ACTION_SHOW_TRACKING_FRAGMENT = "ACTION_SHOW_TRACKING_FRAGMENT"

    /** NOTIFICATION */
    const val NOTIFICATION_CHANNEL_ID = "NOTIFICATION_CHANNEL_ID"
    const val NOTIFICATION_CHANNEL_NAME = "NOTIFICATION_CHANNEL_NAME"
    const val NOTIFICATION_ID = 1

}
